version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1.34.0

jobs:
  build:
    docker:
      - image: circleci/node:16.13.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install -g @angular/cli
      - run: ng build 
      - persist_to_workspace:
          root: .
          paths:
            - dist

  unit-tests:
    docker:
      - image: circleci/node:16.13.2
    steps:
      - attach_workspace:
          at: .
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run unit tests
          command: npm run test

  cypress-tests:
    docker:
      - image: cypress/browsers:node16.13.2-chrome94-ff93
    steps:
      - attach_workspace:
          at: .
      - cypress/install
      - run:
          name: Run Cypress tests
          command: cypress run

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - cypress-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - main