version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - run:
          name: Install Karma CLI
          command: sudo npm install -g karma-cli
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build

  test:
    docker:
      - image: circleci/node:16.13-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - run:
          name: Unit tests
          command: |
            sudo npm install -g karma-cli 
            karma start karma.conf.js --single-run
        finally:
      - run: karma stop
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  e2e:
    docker:
      - image: cypress/included:7.7.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start the app
          command: npm start -- --port 4200
          background: true
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2.1
  build-test-e2e:
    jobs:
      - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
            - test
