version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1.34.0

jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - node/install-packages:
          pkg-list:
            - @angular/cli
      - run: npm install
      - run:
          name: Build
          command: ng build --prod

  unit_tests:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run tests
          command: npm test

  e2e:
    docker:
      - image: cypress/browsers:node16.13.2-chrome99-ff93
    steps:
      - checkout
      - cypress/install
      - cypress/run:
          browser: chrome
          spec: "cypress/integration/*.spec.js"

workflows:
  build_and_test:
    jobs:
      - build
      - unit_tests
      - e2e:
          requires:
            - build
            - unit_tests
