version: 2.1

orbs:
  cypress: cypress-io/cypress@1.24.0

jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build -- --configuration=production

  test:
    docker:
      - image: circleci/node:16.13.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  e2e:
    executor: cypress/browsers
    steps:
      - checkout
      - cypress/install: # Install Cypress dependencies and binary
          version: 8.2.0
      - cypress/run: # Run Cypress tests
          record: true # Record test results to Cypress Dashboard
          parallel: true # Run tests in parallel across multiple machines
          group: "e2e tests" # Group tests in the Cypress Dashboard

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
  test-e2e:
    jobs:
      - e2e:
          requires:
            - build