version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1.34.0

jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - node/install-packages:
          pkg-list: |
            @angular/cli
      - run:
          name: Build App
          command: ng build

  test:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - node/install-packages:
          pkg-list: |
            @angular/cli
            cypress
      - run:
          name: Unit Tests
          command: ng test --watch=false
      - cypress/run:
          record: true
          parallel: true
          group: e2e tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
