version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build

  test:
    docker:
      - image: circleci/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Set Chrome binary path
          command: echo 'export CHROME_BIN=/usr/bin/google-chrome' >> $BASH_ENV
          shell: /bin/bash
      - run:
          name: Unit tests
          command: npm run test

  e2e:
    docker:
      - image: cypress/included:7.7.0
    steps:
      - checkout
      - run:
          name: Set Chrome binary path
          command: echo 'export CHROME_BIN=/usr/bin/google-chrome' >> $BASH_ENV
          shell: /bin/bash
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start the app
          command: npm start -- --port 4200
          background: true
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2.1
  build-test-e2e:
    jobs:
      - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
            - test
