version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build